# ClusterIssuer for Let's Encrypt production using Route53 DNS-01.
# Used by the VPN Certificate. Ensure nodes (or cert-manager) have IAM permissions
# for Route53 in the hosted zone (see aws/iam-policy-route53-dns01.json).
# Replace HOSTED_ZONE_ID with your Route53 hosted zone ID for the domain.
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com  # Replace with your email for Let's Encrypt notifications
    privateKeySecretRef:
      name: letsencrypt-route53
      namespace: cert-manager
    solvers:
      - dns01:
          route53:
            region: us-west-2
            # Least-privilege: restrict to this hosted zone (replace with your zone ID)
            hostedZoneID: HOSTED_ZONE_ID
